# Generated by Django 4.2.20 on 2025-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ad_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='ad_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
